"""add_categories_and_category_id

Revision ID: cd5b2a14347e
Revises: 9428951d372e
Create Date: 2026-04-29 17:29:43.525086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5b2a14347e'
down_revision: Union[str, Sequence[str], None] = '9428951d372e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_base_url', sa.String(length=512), nullable=False),
    sa.Column('api_usage_path', sa.String(length=256), nullable=False),
    sa.Column('api_balance_path', sa.String(length=256), nullable=True),
    sa.Column('tp_base_url', sa.String(length=512), nullable=False),
    sa.Column('tp_usage_path', sa.String(length=256), nullable=False),
    sa.Column('currency_symbol', sa.String(length=16), nullable=False),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('providers', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'providers', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'providers', type_='foreignkey')
    op.drop_column('providers', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
